version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      args:
        WORKDIR:               $WORKDIR
        HOST:                  $HOST
        API_PORT:              $API_PORT
        AWS_ACCESS_KEY_ID:     $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        DB_HOST:               $DB_HOST
        DB_NAME:               $DB_NAME
        DB_USERNAME:           $DB_USERNAME
        DB_PASSWORD:           $DB_PASSWORD
        S3_REGION:             $S3_REGION
        S3_BUCKET:             $S3_BUCKET
        RAILS_MASTER_KEY:      $RAILS_MASTER_KEY
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b ${HOST}"
    volumes:
      - ./api:/$WORKDIR
      - api-bundle:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "$API_PORT:3000"
    # environment:
    #   RAILS_ENV: "production"

  front:
    build:
      context: ./front
      args:
        WORKDIR:           $WORKDIR
        HOST:              $HOST
        FRONT_PORT:        $FRONT_PORT
        API_KEY:           $API_KEY
        AUTH_DOMAIN:       $AUTH_DOMAIN
        PROJECT_ID:        $PROJECT_ID
        DATABASE_URL:      $DATABASE_URL
        STORAGE_BUCKET:    $STORAGE_BUCKET
        MESSAGE_SENDER_ID: $MESSAGE_SENDER_ID
        API_BASE_URL:      $API_BASE_URL
        BROWSER_BASE_URL:  $BROWSER_BASE_URL
        GUEST_EMAIL:       $GUEST_EMAIL
        GUEST_PASSWORD:    $GUEST_PASSWORD
        ADMIN_EMAIL:       $ADMIN_EMAIL
    command: yarn start
    # command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
      - front-node_modules:/app/node_modules
    ports:
      - "$FRONT_PORT:8080"
    depends_on:
      - api
    environment:
      NODE_ENV: "production"

volumes:
  db-data:
  api-bundle:
  front-node_modules: